// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjYQzWmrE5PW_vN5wRcS86oM_CnWzs5zA',
    appId: '1:354590806962:web:fb44a546eb4f334a334aab',
    messagingSenderId: '354590806962',
    projectId: 'peoplecount-b7753',
    authDomain: 'peoplecount-b7753.firebaseapp.com',
    storageBucket: 'peoplecount-b7753.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3VgqMzriie1cq2iHYZsT-Ex0FNj-JWEs',
    appId: '1:354590806962:android:09aff53935a1f40f334aab',
    messagingSenderId: '354590806962',
    projectId: 'peoplecount-b7753',
    storageBucket: 'peoplecount-b7753.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyTqrPRKLOv9zvNBxvntOuaySxCONnVgs',
    appId: '1:354590806962:ios:3ee67424709a53e5334aab',
    messagingSenderId: '354590806962',
    projectId: 'peoplecount-b7753',
    storageBucket: 'peoplecount-b7753.firebasestorage.app',
    iosBundleId: 'com.example.qrCheckApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyTqrPRKLOv9zvNBxvntOuaySxCONnVgs',
    appId: '1:354590806962:ios:3ee67424709a53e5334aab',
    messagingSenderId: '354590806962',
    projectId: 'peoplecount-b7753',
    storageBucket: 'peoplecount-b7753.firebasestorage.app',
    iosBundleId: 'com.example.qrCheckApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjYQzWmrE5PW_vN5wRcS86oM_CnWzs5zA',
    appId: '1:354590806962:web:aac115005b8115d6334aab',
    messagingSenderId: '354590806962',
    projectId: 'peoplecount-b7753',
    authDomain: 'peoplecount-b7753.firebaseapp.com',
    storageBucket: 'peoplecount-b7753.firebasestorage.app',
  );
}
